# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: node-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-cloudbuild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-cloudbuild
  template:
    metadata:
      labels:
        app: nodejs-cloudbuild
    spec:
      containers:
        - name: server
          image: asia-east1-docker.pkg.dev/wingwill-demo-lab-molly/my-repository/nodejs-cloudbuild
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5


